package com;


import Logins.ListGetir;
import Customers.CustEkle;
import Customers.CustomerGonder;
import Customers.CustomerGetir;
import Customers.CustomerInfos;
import Customers.CustSil;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import mssqlCommand.Bilgiler;
import mssqlCommand.BilgilieriGetir;
import java.sql.*;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import mssqlCommand.*;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class Faturaci extends javax.swing.JFrame {
        public static int sayi=0;
        private DefaultListModel basketList;
        private DefaultListModel basketListPrice;
        ListGetir asd=new ListGetir();
        public static int count;
    public void Show_All(){
        
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        
        BilgilieriGetir bilgilist=new BilgilieriGetir(connn);
        ArrayList<Bilgiler> list= bilgilist.getBilgi();
        
        
        Object[] row=new Object[6];
        model.setRowCount(0);
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getId();
            row[1]=list.get(i).getStockCode();
            row[2]=list.get(i).getDescription();
            row[3]=list.get(i).getUnitPrice();
            row[4]=list.get(i).getTaxRate();
            row[5]=list.get(i).getAmount();
            model.addRow(row);
        }    
    }
    
    public void Show_Customer(){
        DefaultTableModel model=(DefaultTableModel)jTable2.getModel();
        
        CustomerGetir custlist=new CustomerGetir(connn);
        ArrayList<CustomerInfos> list=custlist.getCustomer();
        
        Object[] row=new Object[5];
        model.setRowCount(0);
        
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getTaxNo();
            row[1]=list.get(i).getTaxOffice();
            row[2]=list.get(i).getCustName();
            row[3]=list.get(i).getCustAddress();
            row[4]=list.get(i).getCustTel();
            model.addRow(row);
        }
    }
    
    public void Update(){
        IdText.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        jTextField3.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
        jTextField4.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
        jTextField5.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
        int  a=(int) jTable1.getValueAt(jTable1.getSelectedRow(), 4);
        if(a==8){
            jComboBox1.setSelectedIndex(0);
        }else{
            jComboBox1.setSelectedIndex(1);
        }
        int amount=(int) jTable1.getValueAt(jTable1.getSelectedRow(), 5);
        jSpinner1.setValue(amount);
        
        
    }
    
    public void UpdateCustomers(){
        taxno.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString());
        taxoffice.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 1).toString());
        custname.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 2).toString());
        custadress.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 3).toString());
        custtel.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 4).toString());
        
    }
    
    public void ClearText(){
        IdText.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jSpinner1.setValue(0);
    }
    
    
    public static Connection connn=null;
    
    public static Statement stmt;
    public static String EkleSorgusu;
    public static String CustEkle;
    
    
    /**
     * Creates new form Faturaci
     */
    public Faturaci() {
        initComponents();
        Baglan a=new Baglan(connn) {};
        basketList = new DefaultListModel();
        basketListPrice=new DefaultListModel();
        this.connn=a.getBaglan();
        Show_All();
        Show_Customer();
        
        ImageIcon cr1 = new ImageIcon(getClass().getResource("icon.png"));
        this.setIconImage(cr1.getImage());  
        
        ImageIcon cr2 = new ImageIcon(getClass().getResource("logo.png"));
        jLabel2.setIcon(cr2);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        Date = new javax.swing.JLabel();
        InvoiceNo = new javax.swing.JLabel();
        taxno = new javax.swing.JTextField();
        CurrentAccount = new javax.swing.JLabel();
        taxoffice = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Stock = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        Description = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        UnitPrice = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        TaxRate = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        Amount = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        AddButton = new javax.swing.JButton();
        IdText = new javax.swing.JTextField();
        Stock1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        clearbutton = new javax.swing.JButton();
        Tablo = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CurrentAccount1 = new javax.swing.JLabel();
        CurrentAccount2 = new javax.swing.JLabel();
        CurrentAccount3 = new javax.swing.JLabel();
        custadress = new javax.swing.JTextField();
        custname = new javax.swing.JTextField();
        custtel = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        confirm = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Date.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Date.setText("Date : ");
        jPanel3.add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 121, -1, -1));

        InvoiceNo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        InvoiceNo.setText("Tax No:");
        jPanel3.add(InvoiceNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 159, -1, -1));
        jPanel3.add(taxno, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 158, 110, -1));

        CurrentAccount.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        CurrentAccount.setText("Tax Office:");
        jPanel3.add(CurrentAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 197, -1, -1));
        jPanel3.add(taxoffice, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 196, 140, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 3, 13)); // NOI18N
        jLabel4.setText("Create a new Product");

        Stock.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Stock.setText("Stock Code");

        Description.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Description.setText("Description");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        UnitPrice.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        UnitPrice.setText("Unit Price");

        TaxRate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TaxRate.setText("Tax Rate");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "8", "18" }));

        Amount.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Amount.setText("Amount");

        jSpinner1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSpinner1MouseClicked(evt);
            }
        });

        AddButton.setFont(new java.awt.Font("Times New Roman", 3, 13)); // NOI18N
        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        Stock1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Stock1.setText("Id");

        jButton4.setFont(new java.awt.Font("Times New Roman", 3, 13)); // NOI18N
        jButton4.setText("Remove");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        clearbutton.setFont(new java.awt.Font("Times New Roman", 3, 13)); // NOI18N
        clearbutton.setText("Clear Text");
        clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IdText, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Stock1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Stock))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Description))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UnitPrice)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TaxRate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Amount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinner1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Stock)
                            .addComponent(Description)
                            .addComponent(UnitPrice)
                            .addComponent(TaxRate)
                            .addComponent(Amount)
                            .addComponent(Stock1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 32, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 444, 1320, -1));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "StockCode", "Description", "UnitPrice", "TaxRate", "Amount"
            }
        ));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        Tablo.setViewportView(jTable1);

        jPanel3.add(Tablo, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 561, 1320, 200));

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 120, 110, -1));

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(817, 33, 405, 118));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setText("remove at Basket");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 193, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setText("Add to Basket");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 193, 131, -1));

        jLabel1.setText("Total");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1313, 161, -1, -1));

        CurrentAccount1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        CurrentAccount1.setText("Customer Adress:");
        jPanel3.add(CurrentAccount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 274, -1, -1));

        CurrentAccount2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        CurrentAccount2.setText("Customer Name:");
        jPanel3.add(CurrentAccount2, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 237, -1, -1));

        CurrentAccount3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        CurrentAccount3.setText("Customer Tel:");
        jPanel3.add(CurrentAccount3, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 361, -1, -1));
        jPanel3.add(custadress, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 274, 308, 72));
        jPanel3.add(custname, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 236, 308, -1));
        jPanel3.add(custtel, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 360, 140, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Add Customer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 357, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tax_no", "Tax_office", "Customer_name", "Customer_adress", "Customer_tel"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable2MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 236, 660, 202));

        jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList2ValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jList2);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1285, 35, 64, 120));
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1353, 157, -1, -1));

        confirm.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        confirm.setText("Confirm Basket");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        jPanel3.add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(1246, 193, 140, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton5.setText("Remove Customer");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 357, -1, -1));
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 0, 300, 81));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    
    
    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        
        try {
              EkleSorgusu ="INSERT INTO  fatura_tables (Id,StockCode,Description,UnitPrice,TaxRate,Amount) VALUES (?,?,?,?,?,?) ";
        
        
        Ekle veriEkle = new Ekle(connn,Integer.parseInt(IdText.getText()) ,Integer.parseInt(jTextField3.getText()),jTextField4.getText(),Float.parseFloat(jTextField5.getText()),Integer.parseInt( jComboBox1.getSelectedItem().toString()),Integer.parseInt( jSpinner1.getValue().toString()) );
        Show_All();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lütfen Seçim yapınız", "FaturaProgramı" + "", JOptionPane.ERROR_MESSAGE);
        }
      
    }//GEN-LAST:event_AddButtonActionPerformed

    private void jSpinner1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinner1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jSpinner1MouseClicked

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.out.println("Colum: "+jTable1.getSelectedColumn()+" Row:"+jTable1.getSelectedRow());
        basketList.addElement(jTable1.getValueAt(jTable1.getSelectedRow(),2));
        basketListPrice.addElement(jTable1.getValueAt(jTable1.getSelectedRow(),3));
        
        Guncelle b;
        count=Integer.parseInt( jSpinner1.getValue().toString())-1;
        b=new Guncelle(connn, Integer.parseInt(IdText.getText()), Integer.parseInt(jTextField3.getText()), jTextField4.getText(), Float.parseFloat(jTextField5.getText()), Integer.parseInt( jComboBox1.getSelectedItem().toString()), count );
        
        asd.ListEkle(jTable1.getValueAt(jTable1.getSelectedRow(),2).toString(),Double.parseDouble(jTable1.getValueAt(jTable1.getSelectedRow(),3).toString()));

        jList1.setModel(basketList);
        jList2.setModel(basketListPrice);
        System.out.println(jTable1.getValueAt(jTable1.getSelectedRow(),3));
        
        double totalNum = 0;
        
        for(int i=0; i<basketListPrice.size(); i++){
            totalNum += Double.parseDouble(basketListPrice.get(i).toString());
        }
        jLabel5.setText(""+totalNum);
        Show_All();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        asd.ListCikar(jList1.getSelectedValue().toString(),  Double.parseDouble(jList2.getSelectedValue().toString()));
        basketList.remove(jList1.getSelectedIndex());
        basketListPrice.remove(jList2.getSelectedIndex());
        
        Guncelle b;
        count=Integer.parseInt( jSpinner1.getValue().toString())+1;
        b=new Guncelle(connn, Integer.parseInt(IdText.getText()), Integer.parseInt(jTextField3.getText()), jTextField4.getText(), Float.parseFloat(jTextField5.getText()), Integer.parseInt( jComboBox1.getSelectedItem().toString()), count );
        
        double totalNum = 0;
        for(int i=0; i<basketListPrice.size(); i++){
            totalNum += Double.parseDouble(basketListPrice.get(i).toString());
        }
        jLabel5.setText(""+totalNum);
        
        Show_All();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        try {
             Sil veriSil=new Sil(connn, (int) jTable1.getValueAt(jTable1.getSelectedRow(),0));
        Show_All();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lütfen Seçim yapınız", "FaturaProgramı" + "", JOptionPane.ERROR_MESSAGE);
        }

       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:
        Update();
    }//GEN-LAST:event_jTable1MousePressed

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttonActionPerformed
        // TODO add your handling code here:
        ClearText();
    }//GEN-LAST:event_clearbuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CustEkle custEkle = new CustEkle(connn, taxno.getText(), taxoffice.getText(), custname.getText(),custadress.getText(),custtel.getText());
        Show_Customer();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        jList2.setSelectedIndex(jList1.getSelectedIndex());
    }//GEN-LAST:event_jList1ValueChanged

    private void jList2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList2ValueChanged
        // TODO add your handling code here:
        jList1.setSelectedIndex(jList2.getSelectedIndex());
    }//GEN-LAST:event_jList2ValueChanged

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here:
        CustomerGonder a=new CustomerGonder(taxno.getText(), taxoffice.getText(), custname.getText(), custadress.getText(), custtel.getText());
        
        Printer asd=new Printer();
        asd.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_confirmActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        CustSil veriSil=new CustSil(connn, (String) jTable2.getValueAt(jTable2.getSelectedRow(),0));
        Show_Customer();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MousePressed
        // TODO add your handling code here:
        UpdateCustomers();
    }//GEN-LAST:event_jTable2MousePressed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Faturaci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Faturaci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Faturaci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Faturaci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Faturaci().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel Amount;
    private javax.swing.JLabel CurrentAccount;
    private javax.swing.JLabel CurrentAccount1;
    private javax.swing.JLabel CurrentAccount2;
    private javax.swing.JLabel CurrentAccount3;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel Description;
    private javax.swing.JTextField IdText;
    private javax.swing.JLabel InvoiceNo;
    private javax.swing.JLabel Stock;
    private javax.swing.JLabel Stock1;
    private javax.swing.JScrollPane Tablo;
    private javax.swing.JLabel TaxRate;
    private javax.swing.JLabel UnitPrice;
    private javax.swing.JButton clearbutton;
    private javax.swing.JButton confirm;
    private javax.swing.JTextField custadress;
    private javax.swing.JTextField custname;
    private javax.swing.JTextField custtel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField taxno;
    private javax.swing.JTextField taxoffice;
    // End of variables declaration//GEN-END:variables
}
